### ISSUE TITLE
Still have poor performances on Safari and Mobile

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/phasereditor2d-roundedRectangleGraphics-plugin#1]
Using the beta version 1.0.0-beta1
Safari:
<img width="986" alt="image" src="https://user-images.githubusercontent.com/758680/170316589-2cde5629-4008-43ff-ab0a-b51659595151.png">

Chrome: 
<img width="924" alt="image" src="https://user-images.githubusercontent.com/758680/170316966-4a85b19b-7359-4c6e-bc2b-abed8c983a1d.png">

**Comment by PhaserEditor2D** [comment]
Why is it showing that black artifact? Is it Safari on iOS or macOS? Can I test that code?

**Comment by BenoitFreslon** [comment]
I just added 100 rounded rectangles to test.

**Comment by PhaserEditor2D** [comment]
Is it iOS or macOS?

**Comment by PhaserEditor2D** [comment]
What rounded rectangle are you using? The one based on the Graphics object? The one based on the RoundedRectangleImage? I think you should check if graphics objects are performing well there. The RoundedRectangleImage should perform better. The other option you have is using a ninepatch object.

**Comment by BenoitFreslon** [comment]
I'm using both and I tested on Safari Mac and iOS and Android.

![image](https://user-images.githubusercontent.com/758680/170362318-10c35e18-5c6a-4367-8f91-5606cbb57cab.png)
<img width="723" alt="image" src="https://user-images.githubusercontent.com/758680/170362374-2b6e9d97-290c-40b9-bd36-eb3b5f1b749e.png">

![image](https://user-images.githubusercontent.com/758680/170362573-134045fd-15d5-493d-a1da-e6b8e8ddfdc8.png)


<img width="801" alt="image" src="https://user-images.githubusercontent.com/758680/170362402-0d757ff2-f61d-4b29-9ec1-55feeb2959ae.png">

**Comment by PhaserEditor2D** [comment]
And what about the `this.add.roundedRectangleImage(...)`?

**Comment by PhaserEditor2D** [comment]
This is more that 100 RoundedRectangleImage objects in Safari/macOS:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/12187299/170487570-ab17ad38-f398-4c96-80dd-61521bc99cfd.png">

**Comment by PhaserEditor2D** [comment]
And this is the same, but with the RoundedRectangleGraphics:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/12187299/170487865-111374f8-768b-462f-ac97-85cffb775404.png">

It means that writing a lot of graphics objects is expensive (as it says in the Phaser docs). For that reason, I created the RoundedRectagleImage. It creates an image (Phaser.GameObjects.Image) object but generates the rectangle texture on the fly or gets it from the textures cache.

**Comment by BenoitFreslon** [comment]
Indeed I updated correctly all the plugins and I tested images vs graphics.
Here is the result with 100 instances:

```
			// 60 FPS
			//this.add.roundedRectangleImage(i + 100, i + 100, 50, 100);


			// 5 FPS
			//this.add.roundedRectangleGraphics(i + 100, i + 100, 50, 100)

			// 5 FPS
			//this.add.roundedRectangle(i + 100, i + 100, 50, 100);

			// 60 FPS
			//this.add.ninePatchImage(100 + i, 100 + i, 200, 50, "menu", "bg_stars.png")

			// 5 FPS
			// this.add.ninePatch(100 + i, 100 + i, 200, 50, "menu", "bg_stars.png");

			// 60 FPS
			//this.add.ninePatchContainer(100 + i, 100 + i, 200, 50, "menu", "bg_stars.png");
```

**Comment by PhaserEditor2D** [comment]
Good. Then I close this issue. Thanks.
